### ISSUE TITLE
errors in browser while having syntax error in imba file

### ISSUE THREAD

**Issue by madmaniak** [imba/imba#796] opened 2023-01-23 19:43 UTC
### Description

I've been few times confused what happen after having a typo in source
file. Then I find through browser tools that the file is simply not
attached to the bundle (at least with Vite). It would be much faster for a developer to have
an error notice displayed in browser.

### Is this something you're interested in working on?

Yes

**Comment by familyfriendlymikey** [comment] 2023-01-23 19:48
I believe this is only an issue with vite-plugin-imba, likely a duplicate of https://github.com/imba/imba/issues/787.

This has been bothering me a lot, if you'd like to try to fix it I'm sure Abdellah (and I) would be happy :P

**Comment by madmaniak** [comment] 2023-01-23 19:54
OK so it's a bug. If you could only show me the places in code and execution where it works properly?

**Comment by haikyuu** [comment] 2023-01-24 09:53
@madmaniak this is the portion that compiles imba files in the vite plugin https://github.com/imba/imba/blob/master/packages/vite-plugin-imba/src/utils/compile.ts#L75

There should be something off with compilation error handling there

**Comment by madmaniak** [comment] 2023-01-24 13:32
Thank you @haikyuu it was a good starting point. Looks like imba/compiler doesn't throw errors (or catch them before).

I can't see any advice for developing this project (vite-plugin-imba) in README. `npm run dev` seems working, but `npm run build` is throwing an error. So I'm just hacking around so far.

**Comment by madmaniak** [comment] 2023-01-24 13:45
OK there's a flag `raiseError` to be set and it works. Still have no idea how to prepare the package release.

**Comment by madmaniak** [comment] 2023-01-24 13:48
#803

**Comment by haikyuu** [comment] 2023-01-24 14:26
Does that display errors in the browser? I'll try it when i am on the computer

**Closed** 2023-01-25 17:51 UTC
Labels: bug
